/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AnimeRouteImport } from './routes/anime'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TvIndexRouteImport } from './routes/tv.index'
import { Route as TvIdRouteImport } from './routes/tv.$id'
import { Route as MovieIdRouteImport } from './routes/movie.$id'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiProxyRouteImport } from './routes/api/proxy'
import { Route as ApiDownloadRouteImport } from './routes/api/download'
import { Route as ApiTmdbSplatRouteImport } from './routes/api/tmdb.$'
import { Route as ApiMovieTmdbRouteImport } from './routes/api/movie.$tmdb'
import { Route as ApiSubtitlesTypeTmdbRouteImport } from './routes/api/subtitles.$type.$tmdb'
import { Route as ApiSourcesTypeTmdbRouteImport } from './routes/api/sources.$type.$tmdb'
import { Route as ApiTvTmdbSeasonEpisodeRouteImport } from './routes/api/tv.$tmdb.$season.$episode'

const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeRoute = AnimeRouteImport.update({
  id: '/anime',
  path: '/anime',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvIndexRoute = TvIndexRouteImport.update({
  id: '/tv/',
  path: '/tv/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvIdRoute = TvIdRouteImport.update({
  id: '/tv/$id',
  path: '/tv/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIdRoute = MovieIdRouteImport.update({
  id: '/movie/$id',
  path: '/movie/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyRoute = ApiProxyRouteImport.update({
  id: '/api/proxy',
  path: '/api/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadRoute = ApiDownloadRouteImport.update({
  id: '/api/download',
  path: '/api/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTmdbSplatRoute = ApiTmdbSplatRouteImport.update({
  id: '/api/tmdb/$',
  path: '/api/tmdb/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMovieTmdbRoute = ApiMovieTmdbRouteImport.update({
  id: '/api/movie/$tmdb',
  path: '/api/movie/$tmdb',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubtitlesTypeTmdbRoute = ApiSubtitlesTypeTmdbRouteImport.update({
  id: '/api/subtitles/$type/$tmdb',
  path: '/api/subtitles/$type/$tmdb',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSourcesTypeTmdbRoute = ApiSourcesTypeTmdbRouteImport.update({
  id: '/api/sources/$type/$tmdb',
  path: '/api/sources/$type/$tmdb',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTvTmdbSeasonEpisodeRoute = ApiTvTmdbSeasonEpisodeRouteImport.update({
  id: '/api/tv/$tmdb/$season/$episode',
  path: '/api/tv/$tmdb/$season/$episode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anime': typeof AnimeRoute
  '/docs': typeof DocsRoute
  '/downloads': typeof DownloadsRoute
  '/library': typeof LibraryRoute
  '/movies': typeof MoviesRoute
  '/search': typeof SearchRoute
  '/trending': typeof TrendingRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/proxy': typeof ApiProxyRoute
  '/api/status': typeof ApiStatusRoute
  '/movie/$id': typeof MovieIdRoute
  '/tv/$id': typeof TvIdRoute
  '/tv/': typeof TvIndexRoute
  '/api/movie/$tmdb': typeof ApiMovieTmdbRoute
  '/api/tmdb/$': typeof ApiTmdbSplatRoute
  '/api/sources/$type/$tmdb': typeof ApiSourcesTypeTmdbRoute
  '/api/subtitles/$type/$tmdb': typeof ApiSubtitlesTypeTmdbRoute
  '/api/tv/$tmdb/$season/$episode': typeof ApiTvTmdbSeasonEpisodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anime': typeof AnimeRoute
  '/docs': typeof DocsRoute
  '/downloads': typeof DownloadsRoute
  '/library': typeof LibraryRoute
  '/movies': typeof MoviesRoute
  '/search': typeof SearchRoute
  '/trending': typeof TrendingRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/proxy': typeof ApiProxyRoute
  '/api/status': typeof ApiStatusRoute
  '/movie/$id': typeof MovieIdRoute
  '/tv/$id': typeof TvIdRoute
  '/tv': typeof TvIndexRoute
  '/api/movie/$tmdb': typeof ApiMovieTmdbRoute
  '/api/tmdb/$': typeof ApiTmdbSplatRoute
  '/api/sources/$type/$tmdb': typeof ApiSourcesTypeTmdbRoute
  '/api/subtitles/$type/$tmdb': typeof ApiSubtitlesTypeTmdbRoute
  '/api/tv/$tmdb/$season/$episode': typeof ApiTvTmdbSeasonEpisodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anime': typeof AnimeRoute
  '/docs': typeof DocsRoute
  '/downloads': typeof DownloadsRoute
  '/library': typeof LibraryRoute
  '/movies': typeof MoviesRoute
  '/search': typeof SearchRoute
  '/trending': typeof TrendingRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/proxy': typeof ApiProxyRoute
  '/api/status': typeof ApiStatusRoute
  '/movie/$id': typeof MovieIdRoute
  '/tv/$id': typeof TvIdRoute
  '/tv/': typeof TvIndexRoute
  '/api/movie/$tmdb': typeof ApiMovieTmdbRoute
  '/api/tmdb/$': typeof ApiTmdbSplatRoute
  '/api/sources/$type/$tmdb': typeof ApiSourcesTypeTmdbRoute
  '/api/subtitles/$type/$tmdb': typeof ApiSubtitlesTypeTmdbRoute
  '/api/tv/$tmdb/$season/$episode': typeof ApiTvTmdbSeasonEpisodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anime'
    | '/docs'
    | '/downloads'
    | '/library'
    | '/movies'
    | '/search'
    | '/trending'
    | '/api/download'
    | '/api/proxy'
    | '/api/status'
    | '/movie/$id'
    | '/tv/$id'
    | '/tv/'
    | '/api/movie/$tmdb'
    | '/api/tmdb/$'
    | '/api/sources/$type/$tmdb'
    | '/api/subtitles/$type/$tmdb'
    | '/api/tv/$tmdb/$season/$episode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anime'
    | '/docs'
    | '/downloads'
    | '/library'
    | '/movies'
    | '/search'
    | '/trending'
    | '/api/download'
    | '/api/proxy'
    | '/api/status'
    | '/movie/$id'
    | '/tv/$id'
    | '/tv'
    | '/api/movie/$tmdb'
    | '/api/tmdb/$'
    | '/api/sources/$type/$tmdb'
    | '/api/subtitles/$type/$tmdb'
    | '/api/tv/$tmdb/$season/$episode'
  id:
    | '__root__'
    | '/'
    | '/anime'
    | '/docs'
    | '/downloads'
    | '/library'
    | '/movies'
    | '/search'
    | '/trending'
    | '/api/download'
    | '/api/proxy'
    | '/api/status'
    | '/movie/$id'
    | '/tv/$id'
    | '/tv/'
    | '/api/movie/$tmdb'
    | '/api/tmdb/$'
    | '/api/sources/$type/$tmdb'
    | '/api/subtitles/$type/$tmdb'
    | '/api/tv/$tmdb/$season/$episode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimeRoute: typeof AnimeRoute
  DocsRoute: typeof DocsRoute
  DownloadsRoute: typeof DownloadsRoute
  LibraryRoute: typeof LibraryRoute
  MoviesRoute: typeof MoviesRoute
  SearchRoute: typeof SearchRoute
  TrendingRoute: typeof TrendingRoute
  ApiDownloadRoute: typeof ApiDownloadRoute
  ApiProxyRoute: typeof ApiProxyRoute
  ApiStatusRoute: typeof ApiStatusRoute
  MovieIdRoute: typeof MovieIdRoute
  TvIdRoute: typeof TvIdRoute
  TvIndexRoute: typeof TvIndexRoute
  ApiMovieTmdbRoute: typeof ApiMovieTmdbRoute
  ApiTmdbSplatRoute: typeof ApiTmdbSplatRoute
  ApiSourcesTypeTmdbRoute: typeof ApiSourcesTypeTmdbRoute
  ApiSubtitlesTypeTmdbRoute: typeof ApiSubtitlesTypeTmdbRoute
  ApiTvTmdbSeasonEpisodeRoute: typeof ApiTvTmdbSeasonEpisodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime': {
      id: '/anime'
      path: '/anime'
      fullPath: '/anime'
      preLoaderRoute: typeof AnimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/': {
      id: '/tv/'
      path: '/tv'
      fullPath: '/tv/'
      preLoaderRoute: typeof TvIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$id': {
      id: '/tv/$id'
      path: '/tv/$id'
      fullPath: '/tv/$id'
      preLoaderRoute: typeof TvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$id': {
      id: '/movie/$id'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof MovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy': {
      id: '/api/proxy'
      path: '/api/proxy'
      fullPath: '/api/proxy'
      preLoaderRoute: typeof ApiProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download': {
      id: '/api/download'
      path: '/api/download'
      fullPath: '/api/download'
      preLoaderRoute: typeof ApiDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tmdb/$': {
      id: '/api/tmdb/$'
      path: '/api/tmdb/$'
      fullPath: '/api/tmdb/$'
      preLoaderRoute: typeof ApiTmdbSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/movie/$tmdb': {
      id: '/api/movie/$tmdb'
      path: '/api/movie/$tmdb'
      fullPath: '/api/movie/$tmdb'
      preLoaderRoute: typeof ApiMovieTmdbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subtitles/$type/$tmdb': {
      id: '/api/subtitles/$type/$tmdb'
      path: '/api/subtitles/$type/$tmdb'
      fullPath: '/api/subtitles/$type/$tmdb'
      preLoaderRoute: typeof ApiSubtitlesTypeTmdbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sources/$type/$tmdb': {
      id: '/api/sources/$type/$tmdb'
      path: '/api/sources/$type/$tmdb'
      fullPath: '/api/sources/$type/$tmdb'
      preLoaderRoute: typeof ApiSourcesTypeTmdbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tv/$tmdb/$season/$episode': {
      id: '/api/tv/$tmdb/$season/$episode'
      path: '/api/tv/$tmdb/$season/$episode'
      fullPath: '/api/tv/$tmdb/$season/$episode'
      preLoaderRoute: typeof ApiTvTmdbSeasonEpisodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimeRoute: AnimeRoute,
  DocsRoute: DocsRoute,
  DownloadsRoute: DownloadsRoute,
  LibraryRoute: LibraryRoute,
  MoviesRoute: MoviesRoute,
  SearchRoute: SearchRoute,
  TrendingRoute: TrendingRoute,
  ApiDownloadRoute: ApiDownloadRoute,
  ApiProxyRoute: ApiProxyRoute,
  ApiStatusRoute: ApiStatusRoute,
  MovieIdRoute: MovieIdRoute,
  TvIdRoute: TvIdRoute,
  TvIndexRoute: TvIndexRoute,
  ApiMovieTmdbRoute: ApiMovieTmdbRoute,
  ApiTmdbSplatRoute: ApiTmdbSplatRoute,
  ApiSourcesTypeTmdbRoute: ApiSourcesTypeTmdbRoute,
  ApiSubtitlesTypeTmdbRoute: ApiSubtitlesTypeTmdbRoute,
  ApiTvTmdbSeasonEpisodeRoute: ApiTvTmdbSeasonEpisodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
